name: main

on:
  push:
    branches:
      - master

jobs:
  copy_file:
    name: Copy main.yaml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: cp ./main.yaml ./docs/main.yaml